name: Compilar APK Android

on:
  push:
    branches: [ main, master, principal ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Instalar Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Reconstruir estructura oficial de Flutter y Android
        run: |
          # Si la carpeta se creo como 'biblioteca', la renombramos a 'lib'
          if [ -d "biblioteca" ] && [ ! -d "lib" ]; then
            mv biblioteca lib
          fi
          # Generar el andamiaje nativo de Android
          flutter create . --platforms=android --project-name=osciloscopio_app
          flutter pub get

      - name: Compilar APK (Release)
        run: flutter build apk --split-per-abi

      - name: Subir APK para descargar
        uses: actions/upload-artifact@v4
        with:
          name: Osciloscopio-APK
          path: build/app/outputs/flutter-apk/*.apk
